plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':kick-off-core')
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation("com.google.guava:guava:33.0.0-jre")
    implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
    implementation 'com.amazonaws:aws-java-sdk-s3:1.11.1000' // 필요한 AWS SDK를 추가
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

}

test {
    useJUnitPlatform()
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}


